evenement_homepage:
    path:     /
    defaults: { _controller: EvenementBundle:Default:index }

evenements_list:
    path: /evenements_list
    defaults: { _controller: EvenementBundle:Default:ListEvents }
afficher_evnement:
    path: /afficher_evenement/{number}
    defaults: { _controller: EvenementBundle:Default:RenderEvent }
    requirements:
        number: \d+