evenement_homepage:
    path:     /
    defaults: { _controller: EvenementBundle:Default:index }
ajouter_evenement:
    path: /ajouter_evenement
    defaults: { _controller: EvenementBundle:Default:AddEvent }
