services:
#    evenement.example:
#        class: EvenementBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  App\Service\FileUploader:
    arguments:
      $targetDirectory: '%brochures_directory%'
parameters:
  file_directory: '%kernel.project_dir%/public/uploads/brochures'
