<?php

namespace CertificationBundle\Repository;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $userId
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findTestsByUserId($userId){
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT T FROM CertificationBundle:Test T
        WHERE T.User_Test_Affectation = U.User_Test_Affectation AND U.id= :id'
            )->setParameter('id', $userId);

        return $query->getOneOrNullResult();
    }
}
