<?php

namespace CertificationBundle\Repository;

/**
 * UsersTestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersTestsRepository extends \Doctrine\ORM\EntityRepository
{
}
